howToPlayUIonly <- function(){
  tagList(
    tags$h2("Game Overview"),
    tags$p("Playoff Fantasy Football is an elimination based version of Fantasy Football:"),
    tags$ul(
      tags$li("Each contestant will create a diversified roster prior to the start of playoffs."),
      tags$ul(
        tags$li("Your roster must include one player from each of the 14 teams in the playoffs."),
        tags$li("Your roster must include:"),
        tags$ul(
          tags$li("1 Kicker (K)"),
          tags$li("3 Quaterbacks (QB)"),
          tags$li("3 Running Backs (RB)"),
          tags$li("3 Wide Receivers (WR)"),
          tags$li("2 Tight Ends (TE)"),
          tags$li("1 Flex Position (either RB, WR or TE)"),
          tags$li("1 Defense / Special Teams.")
        ),
      ),
      tags$li("The roster will be locked from changes after submission to the Commissioner."),
      tags$ul(
        tags$li("Rosters must be submitted, valid, and paid for by kickoff of the first wildcard game (1pm Saturday, January 13th, 2023)."),
        tags$li("Late rosters will not be accepted."),
        tags$li("Multiple rosters are allowed per Owner, as long as each are paid for.")
      ),
      tags$li("Each week, as teams are eliminated from the playoffs, so does the pool of potential players on your roster who can score points."),
      tags$ul(
        tags$li("Therefore, your overall roster success is as dependent on each player's longevity in the playoffs as much as it is on the player's performance.")
      ),
      tags$li("Fantasy scoring is calculated based on each player's performance during a game."),
      tags$li("The types of statistics converted into Fantasy points is consistent with typical scoring rules (see details below)"),
      tags$li("Points are cumulative throughout the playoffs (including wildcard games and Super Bowl)."),
      tags$li("The person with the most points at the end of the playoffs wins the grand prize."),
      tags$li("Prizes will be awarded to the top 5 scoring entries."),
      tags$li("Prize purse will be announced after wildcard playoff weekend, since prize purse is dependent on the number of entries."),
      tags$li("If you think you're going to win, spread the word: The more participants, the larger the prizes."),
      tags$li("If you think you're going to lose, spread the word: Imagine the commaraderie of shared experience!"),
      tags$li("The Commissioner will (probably) provide weekly updates on Fantasy Team standings throughout the contest. Final summary of scoring and standings will be provided.")
    ),
    tags$h2("How To Use this Dashboard"),
    tags$p("You can use this dashboard to explore player statistics and create your roster:"),
    tags$ul(
      tags$li("Regular season statistics are available on the 'Player Stats' tab, which may help provide insights on each player you should prioritize. Statistics are available in 'football values' and in 'fantasy points'."),
      tags$li("Use the 'Build Roster' tab on this dashboard to start creating your roster."),
      tags$li("Add players to your roster based on the combination you think will score the most points by the end of the Superbowl."),
      tags$li("When a player is added to your roster, the team associated with that player (and any of its remaining players) will be removed from your next possible selections. For example: if you pick Jalen Hurts as one of your quarterbacks, you no longer be able to select an Eagles player on your roster."),
      tags$li("When you've satisified the maximum number of positions on your roster, any player associated with that position will be removed from your next possible selection. For example: if you pick Jalen Hurts as your third (and last) quarterback, you no longer be able to select a quarterback."),
      tags$li("As needed, you can remove players from your team, which will release that Team and/or Position as a next possible selection."),
      tags$li("You must include your Name, Email and Fantasy Team Name in the Participant Information Box. Don't forget to confirm that you've paid the Commish."),
      tags$li("The roster can only be downloaded after all parameters have been satisfied (that is, a completed roster of 14 players and the Participant Information box is filled in with valid information)."),
      tags$li("You must still email the commissioner your roster downloaded from this website. This website does not save your roster.", style="color:red; font-weight:bold;"),
    ),
    # tags$h2("Alternate Roster in Excel"),
    # tags$p("The email sent to you by the Commissioner should contain an Excel file that is equivalent to this dashboard. If you prefer, you can complete that roster template and email the Excel file back to the Commissioner. I don't know why you would do this, but technically it is possible."),
    tags$h2("Scoring"),
    tags$h4("Passing"),
    tags$ul(
      tags$li("TD Pass = 6 points"),
      tags$li("Every 50 passing yards = 1 point"),
      tags$li("400+ Yards in a single game = 2 points"),
      tags$li("40+ Yard Passing TD Bonus = 2 points"),
      tags$li("2pt Passing Conversion = 2 points"),
      tags$li("Interception Thrown = -2 points"),
      tags$li("Fumble Lost = -2 points"),
    ),
    tags$h4("Rushing"),
    tags$ul(
      tags$li("TD Rush = 6 points"),
      tags$li("Every 10 rushing yards = 1 point"),
      tags$li("200+ Yards in a single game = 2 points"),
      tags$li("40+ Yard Passing TD Bonus = 2 points"),
      tags$li("2pt rushing Conversion = 2 points"),
      tags$li("Fumble Lost = -2 points"),
    ),
    tags$h4("Receiving"),
    tags$ul(
      tags$li("TD Receiving = 6 points"),
      tags$li("Every 10 receiving yards = 1 point"),
      tags$li("200+ Yards in a single game = 2 points"),
      tags$li("40+ Yard Receiving TD Bonus = 2 points"),
      tags$li("2pt rushing Conversion = 2 points"),
      tags$li("Fumble Lost = -2 points"),
    ),
    tags$h4("Kicking"),
    tags$ul(
      tags$li("PAT Made = 1 point"),
      tags$li("PAT Missed = -1 point"),
      tags$li("FG Made = 3 points"),
      tags$li("FG Made (40-49 yards) Bonus = 1 point"),
      tags$li("FG Made (50+ yards) Bonus = 2 points"),
      tags$li("FG Missed = -1 point"),
    ),
    tags$h4("Defense / Special Teams"),
    tags$ul(
      tags$li("Each Sack = 1 point"),
      tags$li("Each Interception = 2 points"),
      tags$li("Each Safety = 2 points"),
      tags$li("Each Fumble Recovery = 2 points"),
      tags$li("Each Blocked Punt/PAT/FG = 2 points"),
      tags$li("Interception Return TD = 6 points"),
      tags$li("Fumble Return TD = 6 points"),
      tags$li("Kickoff Return TD = 6 points"),
      tags$li("Punt Return TD = 6 points"),
      tags$li("Blocked Punt or FG Return TD = 6 points"),
      tags$li("0 Points Allowed = 10 points"),
      tags$li("1-6 Points Allowed = 7 points"),
      tags$li("7-13 Points Allowed = 4 points"),
      tags$li("14-17 Points Allowed = 1 points"),
      tags$li("18-21 Points Allowed = 0 points"),
      tags$li("22-27 Points Allowed = -1 points"),
      tags$li("28-34 Points Allowed = -4 points"),
      tags$li("35-45 Points Allowed = -7 points"),
      tags$li("46+ Points Allowed = -10 points")
    )
  )
}